steps:
  - name: 'golang:1.16-buster'
    entrypoint: 'go'
    args: ['build', '.']
    env: ['GO111MODULE=on']
  - name: 'gcr.io/kaniko-project/executor:v1.3.0'
    args:
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/apiserver/$BRANCH_NAME:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=6h
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - golddog
      - --region=asia-northeast1
      - --platform=managed
      - --max-instances=1
      - --cpu=1
      - --memory=256M
      - --concurrency=8
      - --allow-unauthenticated
      - --image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/golddog/$BRANCH_NAME:$COMMIT_SHA